In [1]:
print("Hello World")

Hello World

In [2]:
import pandas as pd

In [3]:
d1 = {
    "names": ["vishwas","alice","john","jack"]
}
s1 = pd.Series(d1)
print(s1)
print(type(s1))

names    [vishwas, alice, john, jack]
dtype: object
<class 'pandas.core.series.Series'>

In [4]:
d2 = {
  "names": ["vishwas","alice","john","jack"],
  "city": ["pune","bangalore", "hyderabad","chennai"]
}
df1 = pd.DataFrame(d2)
print(df1)
print(type(df1))

     names       city
0  vishwas       pune
1    alice  bangalore
2     john  hyderabad
3     jack    chennai
<class 'pandas.core.frame.DataFrame'>

In [5]:
df2 = pd.read_csv("/content/sample_data/california_housing_test.csv")

FileNotFoundError: [Errno 2] No such file or directory: '/content/sample_data/california_housing_test.csv'

In [ ]:
df2.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0

## Preprocessing or cleaning
1. There are any missing values           
    a. Drop the row         
    b. Fill with default value
2. Data Type Formats:          
    Integers, Date Formats

In [ ]:
d3 = {
    "names": ["vishwas","alice","john","jack","Radha"],
    "city": ["pune","bangalore", "hyderabad","chennai","Kochi"],
    "age": [23,24,25,None,"32"],
    "hiredate": ["23/08/2021","12/09/2020",None,"1/9/2021", None]
}

df3 = pd.DataFrame(d3)
df3

     names       city   age    hiredate
0  vishwas       pune    23  23/08/2021
1    alice  bangalore    24  12/09/2020
2     john  hyderabad    25        None
3     jack    chennai  None    1/9/2021
4    Radha      Kochi    32        None

In [ ]:
df3.isna().sum()

names       0
city        0
age         1
hiredate    2
dtype: int64

Drop the rows

In [ ]:
df4 = df3.copy()
df4.dropna()

     names       city age    hiredate
0  vishwas       pune  23  23/08/2021
1    alice  bangalore  24  12/09/2020

When we drop the rows, we will loose the data. If the data is less loosing the data cannot be afforded.

### Filling with default values
1. 0 as minimum for numerical values
2. Means/Median for numerical values
3. "","Notavailable","unknown" for string columns

In [ ]:
df5 = df3.copy()
df5["age"] = df5["age"].fillna(0)
df5["hiredate"] = df5["hiredate"].fillna("1/1/2021")
df5

     names       city age    hiredate
0  vishwas       pune  23  23/08/2021
1    alice  bangalore  24  12/09/2020
2     john  hyderabad  25    1/1/2021
3     jack    chennai   0    1/9/2021
4    Radha      Kochi  32    1/1/2021

In [ ]:
df5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   names     5 non-null      object
 1   city      5 non-null      object
 2   age       5 non-null      object
 3   hiredate  5 non-null      object
dtypes: object(4)
memory usage: 292.0+ bytes

In [ ]:
df6 = df5.copy()
df6["age"] = df6["age"].astype(int)
df6["hiredate"] = pd.to_datetime(df6["hiredate"], dayfirst=True)
df6.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   names     5 non-null      object
 1   city      5 non-null      object
 2   age       5 non-null      int64
 3   hiredate  5 non-null      datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(2)
memory usage: 292.0+ bytes